franka_state_controller:
  type: franka_control/FrankaStateController
  publish_rate: 30  # [Hz]
  arm_id: $(arg arm_id)
  joint_names:
    - $(arg arm_id)_joint1
    - $(arg arm_id)_joint2
    - $(arg arm_id)_joint3
    - $(arg arm_id)_joint4
    - $(arg arm_id)_joint5
    - $(arg arm_id)_joint6
    - $(arg arm_id)_joint7

joint1_controller:
  type: effort_controllers/JointVelocityController
  joint: $(arg arm_id)_joint1
  pid: { p: 600, d: 30, i: 0 }

joint2_controller:
  type: effort_controllers/JointVelocityController
  joint: $(arg arm_id)_joint2
  pid: { p: 600, d: 30, i: 0 }

joint3_controller:
  type: effort_controllers/JointVelocityController
  joint: $(arg arm_id)_joint3
  pid: { p: 600, d: 30, i: 0 }

joint4_controller:
  type: effort_controllers/JointVelocityController
  joint: $(arg arm_id)_joint4
  pid: { p: 600, d: 30, i: 0 }

joint5_controller:
  type: effort_controllers/JointVelocityController
  joint: $(arg arm_id)_joint5
  pid: { p: 250, d: 10, i: 0 }

joint6_controller:
  type: effort_controllers/JointVelocityController
  joint: $(arg arm_id)_joint6
  pid: { p: 150, d: 10, i: 0 }

joint7_controller:
  type: effort_controllers/JointVelocityController
  joint: $(arg arm_id)_joint7
  pid: { p: 50, d: 5, i: 0 }


